# Generated by Django 3.2.10 on 2022-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_asked_for_activ',
            field=models.BooleanField(default=False),
        ),
    ]
