# Generated by Django 3.2.10 on 2022-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_asked_for_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('img_src', models.ImageField(upload_to='images/social')),
                ('email_content', models.TextField(verbose_name="Содержание email'a")),
                ('instagram_link', models.CharField(max_length=200, verbose_name='Ссылка на Инстаграм пост')),
                ('facebook_link', models.CharField(max_length=200, verbose_name='Ссылка на Фейсбук пост')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация отправлена?')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации в соц.сетях',
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
