# Generated by Django 3.2.10 on 2022-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220127_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenworkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва (uk)')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка')),
                ('img_src', models.CharField(help_text='Пример: images/social/image.jpg', max_length=100, verbose_name='Название фотографии')),
                ('post_content_ru', models.TextField(verbose_name="Содержание post'a")),
                ('post_content_uk', models.TextField(blank=True, null=True, verbose_name="Змiст post'a (uk)")),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации блога',
                'ordering': ['-published'],
            },
        ),
    ]
