# Generated by Django 3.2.10 on 2022-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teenworkblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenworkblog',
            name='img_src',
            field=models.CharField(help_text='Пример: images/social/image.jpg', max_length=200, verbose_name='Название фотографии'),
        ),
    ]
