# Generated by Django 3.2.10 on 2022-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_teenworkblog_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва (uk)')),
                ('img_src', models.CharField(help_text='Пример: images/social/image.jpg', max_length=100, verbose_name='Название фотографии')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Змiст (uk)')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма рассылки',
                'ordering': ['-published'],
            },
        ),
    ]
