# Generated by Django 3.2.10 on 2022-12-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='region',
        ),
    ]
