name: "teenwork"

x-common-variables: &common-variables
  - DATABASE_USER=teenwork
  - DATABASE_NAME=teenwork
  - DATABASE_PASSWORD=teenwork
  - DATABASE_HOST=database
  - DATABASE_PORT=5432
  
services:
  database:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: *common-variables
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

  server:
    build: 
      dockerfile: ./containers/server/Dockerfile
    command: ["sh", "-c", "/var/teenwork/run.sh"]
    # command: ["python", "manage.py", "runserver"]
    volumes:
      - ./backend/:/var/teenwork
      - static_volume:/var/teenwork/static
      - media_volume:/var/teenwork/media
    # WIth expose port 8000 is only exposed internally, to other Docker services. The port will no longer be published to the host machine.
    # expose:
    #   - 8000
    ports:
      - 80:80
    environment: *common-variables
    env_file:
      - ./backend/.env
    depends_on:
      - database
      - frontend

  frontend:
    container_name: frontend
    build:
      dockerfile: ./containers/frontend/Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


volumes:
  postgres_data:
  static_volume:
  media_volume: