# Generated by Django 3.2.10 on 2022-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='im_working_student',
            field=models.BooleanField(default=False),
        ),
    ]
