# Generated by Django 3.2.10 on 2021-12-12 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Чат')),
                ('ad_fk', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='Объявление №')),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники чата')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000, verbose_name='Сообщение')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отправки')),
                ('sender', models.CharField(blank=True, max_length=10000, verbose_name='Отправитель')),
                ('receiver', models.CharField(blank=True, max_length=10000, verbose_name='Получатель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room', verbose_name='Чат №')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
