# Generated by Django 3.2.10 on 2022-12-29 09:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20221226_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='name_uk',
        ),
        migrations.AddField(
            model_name='teenworkblog',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Содержание post'a"),
        ),
        migrations.AddField(
            model_name='teenworkblog',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Содержание post'a"),
        ),
        migrations.AddField(
            model_name='teenworkblog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='teenworkblog',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
