# Generated by Django 3.2.10 on 2021-12-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.BooleanField(default=False, null=True, verbose_name='Telegram')),
                ('chat_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='chat id')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.age', verbose_name='Возраст')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.city', verbose_name='Город')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Человек')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.region', verbose_name='Область')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['telegram'],
            },
        ),
    ]
