# Generated by Django 3.2.10 on 2022-12-23 21:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраста',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, max_length=5500, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('workers_amount', models.IntegerField(blank=True, null=True, verbose_name='Кол-во работников')),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='Имя автора')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('published', 'Published'), ('edited', 'Edited'), ('draft', 'Draft'), ('archive', 'Archive'), ('24hour', '24hour'), ('24hour_draft', '24hour_draft')], default='draft', max_length=20)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.age', verbose_name='Возраст')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюта',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeenworkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Содержание post'a")),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации блога',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeletedAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('content', models.TextField(blank=True, max_length=5500, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('published', models.DateTimeField(db_index=True, editable=False, verbose_name='Опубликовано')),
                ('region', models.CharField(max_length=100, null=True, verbose_name='Область')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('workers_amount', models.IntegerField(blank=True, null=True, verbose_name='Кол-во работников')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор')),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='Имя автора')),
                ('phone_number', models.CharField(blank=True, max_length=13, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(blank=True, max_length=20)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.age', verbose_name='Возраст')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.currency', verbose_name='Валюта')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.rubric', verbose_name='Рубрика')),
                ('workers', models.ManyToManyField(blank=True, default=None, related_name='deleted_adt_workers', to=settings.AUTH_USER_MODEL, verbose_name='Принятые на работу')),
            ],
            options={
                'verbose_name': 'Удал. объявление',
                'verbose_name_plural': 'Удалённые объявления',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='board',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='Понравившиеся публикации'),
        ),
        migrations.AddField(
            model_name='board',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.rubric', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='board',
            name='workers',
            field=models.ManyToManyField(blank=True, default=None, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='Принятые на работу'),
        ),
    ]
