# Generated by Django 3.2.10 on 2022-01-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
