# Generated by Django 3.2.10 on 2022-12-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_deletedads_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='region',
        ),
    ]
