# Generated by Django 3.2.10 on 2022-12-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_board_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='age_to',
        ),
        migrations.RemoveField(
            model_name='deletedads',
            name='age_to',
        ),
    ]
