# Generated by Django 3.2.10 on 2023-06-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20221229_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teenworkblog',
            old_name='content_ru',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='teenworkblog',
            old_name='title_ru',
            new_name='title_en',
        ),
    ]
